# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
  service vpp stop
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "uliege/tracebox"
  config.vm.box_url = ["http://queen.run.montefiore.ulg.ac.be/~edeline/trace.box", "https://erg.abdn.ac.uk/~iain/trace.box"]
  
  config.vm.hostname = "tracebox-tutorial"
  config.vm.define "tracebox-tutorial"
  config.vm.post_up_message = "Welcome to the RCM tutorial !"

  config.vm.provision :shell, :inline => $script

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
      vb.name = "mmb-tutorial"
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.memory = "4096"
      vb.cpus = "2"

      #support for the SSE4.x instruction is required in some versions of VB.
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
  end
end

